openapi: 3.0.0
info:
  title: Knowlance AI Website API
  version: 1.0.0
  description: API for the Knowlance AI website, including demo requests, community forum, and team information.

paths:
  /waitlist-subscriptions:
    post:
      summary: Subscribe to the MVP waitlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WaitlistSubscription'
      responses:
        '201':
          description: Successfully subscribed
        '400':
          description: Invalid input

  /demo-requests:
    post:
      summary: Submit a demo request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemoRequest'
      responses:
        '201':
          description: Demo request submitted successfully
        '400':
          description: Invalid input

  /team-members:
    get:
      summary: Get the list of team members
      responses:
        '200':
          description: A list of team members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TeamMember'

  /community/topics:
    get:
      summary: Get a list of community topics
      parameters:
        - in: query
          name: sort
          schema:
            type: string
            enum: [recent, popular]
          description: Sort order for topics
        - in: query
          name: limit
          schema:
            type: integer
          description: Maximum number of topics to return
      responses:
        '200':
          description: A list of community topics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommunityTopic'
    post:
      summary: Create a new community topic
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCommunityTopic'
      responses:
        '201':
          description: Topic created successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized

  /community/topics/{topicId}:
    get:
      summary: Get a single community topic with replies
      parameters:
        - in: path
          name: topicId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The community topic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommunityTopicWithReplies'
        '404':
          description: Topic not found

  /community/topics/{topicId}/replies:
    post:
      summary: Post a reply to a community topic
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: topicId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewReply'
      responses:
        '201':
          description: Reply posted successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Topic not found

  /users/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input or user already exists

  /users/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials

components:
  schemas:
    WaitlistSubscription:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
        - email

    DemoRequest:
      type: object
      properties:
        fullName:
          type: string
        workEmail:
          type: string
          format: email
        companyName:
          type: string
        role:
          type: string
        challenge:
          type: string
        objective:
          type: string
        technicalRequirements:
          type: string
      required:
        - fullName
        - workEmail
        - challenge

    TeamMember:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        title:
          type: string
        bio:
          type: string
        imageUrl:
          type: string
          format: uri
        linkedinUrl:
          type: string
          format: uri
        githubUrl:
          type: string
          format: uri

    CommunityTopic:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          $ref: '#/components/schemas/User'
        createdAt:
          type: string
          format: date-time
        repliesCount:
          type: integer

    CommunityTopicWithReplies:
      allOf:
        - $ref: '#/components/schemas/CommunityTopic'
        - type: object
          properties:
            replies:
              type: array
              items:
                $ref: '#/components/schemas/CommunityReply'

    NewCommunityTopic:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content

    CommunityReply:
      type: object
      properties:
        id:
          type: integer
        author:
          $ref: '#/components/schemas/User'
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    NewReply:
      type: object
      properties:
        content:
          type: string
      required:
        - content

    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        avatarUrl:
          type: string
          format: uri
        isStaff:
          type: boolean

    UserRegistration:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - username
        - email
        - password

    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
