openapi: 3.0.0
info:
  title: Knowlance AI Website API
  version: 1.0.0
  description: API specification for the Knowlance AI website frontend-backend communication.

paths:
  /demo-requests:
    post:
      summary: Submit a demo request
      description: Submits the client's request for a product demo.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DemoRequest'
      responses:
        '201':
          description: Demo request submitted successfully.
        '400':
          description: Invalid input.

  /mvp-waitlist:
    post:
      summary: Join the MVP waitlist
      description: Adds a user's email to the waitlist for the AI Data Analyst MVP.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
      responses:
        '201':
          description: Email added to the waitlist.
        '400':
          description: Invalid email format.

  /community/topics:
    get:
      summary: Get discussion topics
      description: Retrieves a list of topics from the community forum.
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: A list of topics.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Topic'
    post:
      summary: Create a new topic
      description: Creates a new discussion topic in the community forum.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTopic'
      responses:
        '201':
          description: Topic created successfully.
        '400':
          description: Invalid input.
        '401':
          description: Unauthorized.

  /community/topics/{topicId}:
    get:
      summary: Get a topic by ID
      description: Retrieves a single topic and its posts by its ID.
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The requested topic with its posts.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopicWithPosts'
        '404':
          description: Topic not found.

  /community/topics/{topicId}/posts:
    post:
      summary: Post a reply to a topic
      description: Adds a new post (reply) to an existing topic.
      security:
        - bearerAuth: []
      parameters:
        - name: topicId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPost'
      responses:
        '201':
          description: Reply posted successfully.
        '400':
          description: Invalid input.
        '401':
          description: Unauthorized.
        '404':
          description: Topic not found.

  /users/register:
    post:
      summary: Register a new user
      description: Registers a new user for the community.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegistration'
      responses:
        '201':
          description: User registered successfully.
        '400':
          description: Invalid input or user already exists.

  /users/login:
    post:
      summary: User login
      description: Authenticates a user and returns a JWT token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Invalid credentials.

components:
  schemas:
    DemoRequest:
      type: object
      properties:
        fullName:
          type: string
        workEmail:
          type: string
          format: email
        companyName:
          type: string
        role:
          type: string
        challenge:
          type: string
        objective:
          type: string
        technicalRequirements:
          type: string
      required:
        - fullName
        - workEmail
        - companyName
        - role
        - challenge
        - objective

    Topic:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          $ref: '#/components/schemas/User'
        createdAt:
          type: string
          format: date-time
        postCount:
          type: integer

    NewTopic:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
      required:
        - title
        - content

    TopicWithPosts:
      allOf:
        - $ref: '#/components/schemas/Topic'
        - type: object
          properties:
            posts:
              type: array
              items:
                $ref: '#/components/schemas/Post'

    Post:
      type: object
      properties:
        id:
          type: string
        author:
          $ref: '#/components/schemas/User'
        content:
          type: string
        createdAt:
          type: string
          format: date-time

    NewPost:
      type: object
      properties:
        content:
          type: string
      required:
        - content

    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        isStaff:
          type: boolean

    UserRegistration:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - username
        - email
        - password

    UserLogin:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
