openapi: 3.0.0
info:
  title: "Knowlance AI Core API"
  version: "1.0.0"
  description: "API for managing users, projects, and the community forum."

paths:
  /users:
    post:
      summary: "Register a new user"
      # ... OpenAPI spec for user registration ...
  /users/{userId}:
    get:
      summary: "Get user details"
      # ... OpenAPI spec for getting user ...
    put:
      summary: "Update user details"
      # ... OpenAPI spec for updating user ...

  /projects:
    get:
      summary: "List all projects for the current user"
      # ... OpenAPI spec for listing projects ...
    post:
      summary: "Submit a new project for scoping"
      # ... OpenAPI spec for creating a project ...

  /projects/{projectId}:
    get:
      summary: "Get details of a specific project"
      # ... OpenAPI spec for getting a project ...
    put:
      summary: "Update a project"
      # ... OpenAPI spec for updating a project ...

  /forum/categories:
    get:
      summary: "List all forum categories"
      # ... OpenAPI spec for listing categories ...

  /forum/threads:
    get:
      summary: "List threads (can be filtered by category)"
      # ... OpenAPI spec for listing threads ...
    post:
      summary: "Create a new thread"
      # ... OpenAPI spec for creating a thread ...

  /forum/threads/{threadId}/posts:
    get:
      summary: "List all posts in a thread"
      # ... OpenAPI spec for listing posts ...
    post:
      summary: "Create a new post in a thread"
      # ... OpenAPI spec for creating a post ...